travis:
  secure:
    BINSTAR_TOKEN: YSodV+J8//uElRPMvBy08hproq2774QKfHo+ZEY73bC68G9B+nzV3tfegb2n8qPWHXU3DwfQiyrZaIOZVVvQ8lCqfp6ZV25B/Q5Xme6sk+LbKCcHQdn0gwwkltZyXzDovjetiHAo5m9cHpp56v35KxTzFmoykdfAbLcofOBDVr+TK3mrRNt30tzdPX4apBZL96OR82jBu0Dz15zmii0PMd0BiPJb8eYcYZDpfFFidaw7WGfsghnw8nn/FfrTnyxg5t/YmLdNvwo0ezfIGIsL+998QkkIusA8mAF7iF21HYvoIhUeXNa4zo0VqlA68nr3eLMWBCJj/pT/kvyxDcwCJhdnYdq5bbUAjK4ecWcMiFs615nUDO3kFi2y/jPfqcO+AjrWnGVgIyZijLtnlzHJXFBy2Go1vELWJ/jBFZCOESjDbSpL1Gz73QEhTYSvwTURRRoiEZ2sPPjz2kTaB1xZIs8yBO3pNL9g2EAoxvwUeL9NYH8rsOy8T7CskEi5SS8vqBp/uhJHzSVPYdr92nbQOAB1riIY+85f3GoPDrLYDBcJqx4kyssVY5s4z8Nwrui8kKPQxuO3t8W4HI3xTH98enfdUB/TjkgiMKymyZaz0zY+CvXKwRRlXdC5GUlajvIfZ45jjiyElnfxx9Kw9bxOTBvHT5zzF5TfxyGDoaKUShE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
