travis:
  secure:
    BINSTAR_TOKEN: TbqVK9WByE48LxBTpkkPrLbhyWLrir8t+p4nzR4Hb9jJaacN083LvcYDZRSF/arXw57XkHi8myK8ZrWknh5I3LQPGeilCnjsU4s2gnlfAgGNreGwByZ6J5qqHNBKjwSVVKM3CRQDWwv2cPF2Wh/UREh7FisSft0ZHGNO7yw34fQHHqx9hUjUMCvs+B8sL4ZNz52g2bMaOV7o51cXi6G6JsErgaaMfWtmXlvkeJlXqyACYT0grXNNSRMiWLkX6/ODwJ59CS+wM0NYGsoNStSnDpkruiICxO1y52Q/nUbnsQtwnTWtNJZF1V/AYmwvr900I+KOGM5scAT9PHi9wwrhjm0A3kdhSBvTz0ySA5xwbgC8+bVFj597pWFm/hxmoWsPMVuq0JSGXDvEl6PLfxu28OYloHxr0H3e0RaTpNaOOFWDRZP8nPeoPVcJLFM8IYyXGWZ61z4eacdxlmS5kKP9zoe6pWLgZh5GCX5Jj8dPz6gKSToi9UkiL11zGCxNRc6K3znJeVm352/1GpnjKuxLGiCS9eubKnvVNnJ+DLFBTk7T1rTAmorFDyzP+ncJ0RqYzESEQMWjr4i5PV+l2ydxBQUiTy0u8HHmI8ZL4+7xgq2lX0kj1T6H3Y6UBHb6rB6VeF7N7lZaxwxuZEQbNJxS1WWRYxanJh4T40iQgieBTf8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
